name = "NLboxsolve"
uuid = "57734975-34ee-4662-b82a-2ecfa01d03df"
authors = ["Richard Dennis <richard.dennis@glasgow.ac.uk>"]
version = "0.4.8"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "^1.6"
ForwardDiff = "^0.10"